/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AETermoLogico extends PTermoLogico
{
    private PTermoLogico _termoLogico_;
    private TE _e_;
    private PFatorLogico _fatorLogico_;

    public AETermoLogico()
    {
        // Constructor
    }

    public AETermoLogico(
        @SuppressWarnings("hiding") PTermoLogico _termoLogico_,
        @SuppressWarnings("hiding") TE _e_,
        @SuppressWarnings("hiding") PFatorLogico _fatorLogico_)
    {
        // Constructor
        setTermoLogico(_termoLogico_);

        setE(_e_);

        setFatorLogico(_fatorLogico_);

    }

    @Override
    public Object clone()
    {
        return new AETermoLogico(
            cloneNode(this._termoLogico_),
            cloneNode(this._e_),
            cloneNode(this._fatorLogico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAETermoLogico(this);
    }

    public PTermoLogico getTermoLogico()
    {
        return this._termoLogico_;
    }

    public void setTermoLogico(PTermoLogico node)
    {
        if(this._termoLogico_ != null)
        {
            this._termoLogico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoLogico_ = node;
    }

    public TE getE()
    {
        return this._e_;
    }

    public void setE(TE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public PFatorLogico getFatorLogico()
    {
        return this._fatorLogico_;
    }

    public void setFatorLogico(PFatorLogico node)
    {
        if(this._fatorLogico_ != null)
        {
            this._fatorLogico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fatorLogico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoLogico_)
            + toString(this._e_)
            + toString(this._fatorLogico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoLogico_ == child)
        {
            this._termoLogico_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._fatorLogico_ == child)
        {
            this._fatorLogico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoLogico_ == oldChild)
        {
            setTermoLogico((PTermoLogico) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((TE) newChild);
            return;
        }

        if(this._fatorLogico_ == oldChild)
        {
            setFatorLogico((PFatorLogico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
