/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AIdentificador extends PIdentificador
{
    private TIdVar _idVar_;

    public AIdentificador()
    {
        // Constructor
    }

    public AIdentificador(
        @SuppressWarnings("hiding") TIdVar _idVar_)
    {
        // Constructor
        setIdVar(_idVar_);

    }

    @Override
    public Object clone()
    {
        return new AIdentificador(
            cloneNode(this._idVar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentificador(this);
    }

    public TIdVar getIdVar()
    {
        return this._idVar_;
    }

    public void setIdVar(TIdVar node)
    {
        if(this._idVar_ != null)
        {
            this._idVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idVar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idVar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idVar_ == child)
        {
            this._idVar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idVar_ == oldChild)
        {
            setIdVar((TIdVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
