/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AStart extends PStart
{
    private PProgramaStatement _programaStatement_;

    public AStart()
    {
        // Constructor
    }

    public AStart(
        @SuppressWarnings("hiding") PProgramaStatement _programaStatement_)
    {
        // Constructor
        setProgramaStatement(_programaStatement_);

    }

    @Override
    public Object clone()
    {
        return new AStart(
            cloneNode(this._programaStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStart(this);
    }

    public PProgramaStatement getProgramaStatement()
    {
        return this._programaStatement_;
    }

    public void setProgramaStatement(PProgramaStatement node)
    {
        if(this._programaStatement_ != null)
        {
            this._programaStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programaStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programaStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programaStatement_ == child)
        {
            this._programaStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programaStatement_ == oldChild)
        {
            setProgramaStatement((PProgramaStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
